export const UNAUTHENTICATED = 'UNAUTHENTICATED';
export const BAD_USER_INPUT = 'BAD_USER_INPUT';
export const TOO_MANY_MOCK_ENDPOINTS = 'TOO_MANY_MOCK_ENDPOINTS';
export const GRAPHQL_VALIDATION_FAILED = 'GRAPHQL_VALIDATION_FAILED';
